---
title: "Gini impurity"
author: "SK"
output: 
  rmarkdown::html_document:
    toc: true
    toc_depth: 1
vignette: >
  %\VignetteIndexEntry{}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r, include = FALSE}
source(file = "~/Rutil/Init_Rpack.R")
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F,
                      comment = F, 
                      warning = F, 
                      message = F)
```



```{r, echo = T, eval = F, results='hide'}
library(scBubbletree)
library(Seurat)
library(ggrepel)
```


```{r, echo = F, results='hide'}
library(scBubbletree)
library(Seurat, lib.loc = lib.loc)
library(ggrepel, lib.loc = lib.loc)
```




```{r}

get_clusters_graph <- function(d, res, reduction_type, dims, labels) {
  
    d <- Seurat::FindNeighbors(object = d, 
                               reduction = reduction_type, 
                               dims = dims)
    c <- Seurat::FindClusters(object = d, 
                              resolution = 10^res,
                              n.start = 100,
                              n.iter = 100)
    cs <- as.character(c$seurat_clusters)
    g2 <- get_gini(labels = labels, clusters = cs)

    return(data.frame(res = 10^as.numeric(res),
                      k = length(unique(cs)),
                      gini = g2$total_gini,
                      reduction_type = reduction_type))
}

```


```{r}

get_kmeans <- function(x, a, labels) {
  
  km <- kmeans(x = a, 
         centers = x, 
         iter.max = 1000, 
         nstart = 500, 
         algorithm = "MacQueen")
  
    
    cs <- as.character(km$cluster)
    g <- get_gini(labels = labels, clusters = cs)

    return(data.frame(res = NA,
                      k = x,
                      gini = g$total_gini))
}

```


# Study B

```{r}
d <- get(load(file = "case_study_B/Hao_2021.RData"))
```


```{r}
leuven_umap <- mclapply(X = seq(from = -4, to = 0, by = 0.05), 
                        FUN = get_clusters_graph, 
                        d = d,
                        labels = d@meta.data$celltype.l2,
                        dims = 1:2, 
                        reduction_type = "umap",
                        mc.cores = 15)

leuven_umap <- do.call(rbind, leuven_umap)

save(leuven_umap, file = "case_study_B/leuven_umap.RData")
```




```{r}
leuven_tsne <- mclapply(X = seq(from = -4, to = 0, by = 0.05), 
                        FUN = get_clusters_graph, 
                        d = d,
                        labels = d@meta.data$celltype.l2,
                        dims = 1:2, 
                        reduction_type = "tsne",
                        mc.cores = 15)

leuven_tsne <- do.call(rbind, leuven_tsne)

save(leuven_tsne, file = "case_study_B/leuven_tsne.RData")
```


```{r}
leuven_pca <- mclapply(X = seq(from = -4, to = 1, by = 0.05), 
                       FUN = get_clusters_graph, 
                       d = d,
                       labels = d@meta.data$celltype.l2,
                       dims = 1:15, 
                       reduction_type = "pca",
                       mc.cores = 15)
leuven_pca <- do.call(rbind, leuven_pca)
save(leuven_pca, file = "case_study_B/leuven_pca.RData")
```


```{r}
a <- d@reductions$pca@cell.embeddings[, 1:15]
l2 <- d@meta.data$celltype.l2
rm(d); 
gc();gc();gc()

kms <- mclapply(X = 1:50,
                FUN = get_kmeans, 
                a = a[, 1:15],
                labels = l2,
                mc.cores = 20)
kms <- do.call(rbind, kms)
save(kms, file = "case_study_B/kms.RData")
```




# Study A

```{r}
d <- get(load(file = "case_study_A/d.RData"))
```


```{r}
leuven_umap <- mclapply(X = seq(from = -4, to = 1, by = 0.05), 
                        FUN = get_clusters_graph, 
                        d = d,
                        dims = 1:2, 
                        labels = d@meta.data$cell_line_demuxlet,
                        reduction_type = "umap",
                        mc.cores = 15)
leuven_umap <- do.call(rbind, leuven_umap)
save(leuven_umap, file = "case_study_A/leuven_umap.RData")
```




```{r}
leuven_tsne <- mclapply(X = seq(from = -4, to = 1, by = 0.05), 
                        FUN = get_clusters_graph, 
                        d = d,
                        dims = 1:2, 
                        labels = d@meta.data$cell_line_demuxlet,
                        reduction_type = "tsne",
                        mc.cores = 15)
leuven_tsne <- do.call(rbind, leuven_tsne)
save(leuven_tsne, file = "case_study_A/leuven_tsne.RData")
```


```{r}
leuven_pca <- mclapply(X = seq(from = -4, to = 1, by = 0.05), 
                       FUN = get_clusters_graph, 
                       d = d,
                       dims = 1:15, 
                       labels = d@meta.data$cell_line_demuxlet,
                       reduction_type = "pca",
                       mc.cores = 15)
leuven_pca <- do.call(rbind, leuven_pca)
save(leuven_pca, file = "case_study_A/leuven_pca.RData")
```


```{r}
a <- d@reductions$pca@cell.embeddings[, 1:15]
gc();gc();gc()

kms <- mclapply(X = 1:50,
                FUN = get_kmeans, 
                a = a[, 1:15],
                labels = d$cell_line_demuxlet,
                mc.cores = 20)
kms <- do.call(rbind, kms)
save(kms, file = "case_study_A/kms.RData")
```



# Visualization

```{r}
kms <- get(load(file = "case_study_A/kms.RData"))
kms$reduction_type <- "kmeans"
leuven_tsne <- get(load(file = "case_study_A/leuven_tsne.RData"))
leuven_umap <- get(load(file = "case_study_A/leuven_umap.RData"))
leuven_pca <- get(load(file = "case_study_A/leuven_pca.RData"))


gini_A <- rbind(kms, leuven_tsne, leuven_umap, leuven_pca)
rm(leuven_tsne, leuven_umap, leuven_pca, kms)
```


```{r, fig.width=5, fig.height=3.75}
gini_A <- aggregate(gini~k+reduction_type, data = gini_A, FUN = mean)

g_a <- ggplot(data = gini_A)+
  facet_wrap(facets = ~reduction_type, nrow = 2)+
  geom_line(aes(x = k, y = gini))+
  geom_point(aes(x = k, y = gini), size = 1)+
  ylim(c(0,1))+
  ylab(label = "Gini impurity (cell line)")+
  xlim(c(0, 50))+
  theme_bw(base_size = 10)+
  theme(legend.position = "top")

g_a
```


```{r, fig.width=5, fig.height=3.75}
g_a2 <- ggplot(data = gini_A)+
  geom_line(aes(x = k, y = gini, col = reduction_type), 
            size = 0.8, alpha = 0.8)+
  ylab(label = "Gini impurity (cell line)")+
  xlim(c(0, 50))+
  theme_bw(base_size = 10)+
  theme(legend.position = "top")+
  scale_color_grey(name = "clustering")

g_a2
```


```{r}
kms <- get(load(file = "case_study_B/kms.RData"))
kms$reduction_type <- "kmeans"
leuven_tsne <- get(load(file = "case_study_B/leuven_tsne.RData"))
leuven_umap <- get(load(file = "case_study_B/leuven_umap.RData"))
leuven_pca <- get(load(file = "case_study_B/leuven_pca.RData"))


gini_B <- rbind(kms, leuven_tsne, leuven_umap, leuven_pca)
rm(kms, leuven_tsne, leuven_umap, leuven_pca)
```

```{r, fig.width=4, fig.height=4}
gini_B <- aggregate(gini~k+reduction_type, data = gini_B, FUN = mean)

g_b <- ggplot(data = gini_B)+
  facet_wrap(facets = ~reduction_type, nrow = 2)+
  geom_line(aes(x = k, y = gini))+
  geom_point(aes(x = k, y = gini), size = 1)+
  ylim(c(0,1))+
  ylab(label = "Gini impurity (annotation set l2)")+
  xlim(c(0, 50))+
  theme_bw(base_size = 10)+
  theme(legend.position = "top")

g_b
```


```{r, fig.width=4, fig.height=4}
g_b2 <- ggplot(data = gini_B)+
  geom_line(aes(x = k, y = gini, col = reduction_type), 
            size = 0.8, alpha = 0.8)+
  ylab(label = "Gini impurity (annotation set l2)")+
  xlim(c(0, 50))+
  theme_bw(base_size = 10)+
  theme(legend.position = "top")+
  scale_color_grey(name = "clustering")+
  scale_linetype(name = "clustering")
  

g_b2
```

```{r}
g_a|g_b
```

```{r, fig.width=6.5, fig.height=4}
g <- (g_a2|g_b2)+
  patchwork::plot_annotation(tag_levels = 'A')

g
```


```{r, fig.width=6.5, fig.height=4}
ggsave(filename = "manuscript_data/Supplementary_gini_curves.pdf",
       plot = g,
       device = "pdf",
       width = 6.75,
       height = 4)
```





```{r, fig.width=6, fig.height=3}
g <- (g1|g2|g3)+
  patchwork::plot_layout(widths = c(1,1,1))+
  patchwork::plot_annotation(tag_levels = 'A')

ggsave(filename = "manuscript_data/Supplementary_gini_curves.pdf",
       plot = g,
       device = "pdf",
       width = 6.75,
       height = 3)
```

