---
title: "Supplementary figures"
author: "SK"
output: 
  rmarkdown::html_document:
    toc: true
    toc_depth: 1
vignette: >
  %\VignetteIndexEntry{}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r, include = FALSE}
source(file = "~/Rutil/Init_Rpack.R")
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F,
                      comment = F, 
                      warning = F, 
                      message = F)
```


```{r, echo = T, results='hide'}
source(file = "../Rutil/Graphics.R")

source(file = "../scBubbletree/R/util.R")
source(file = "../scBubbletree/R/main.R")
source(file = "../scBubbletree/R/annotation.R")
```


```{r, echo = T, results='hide'}
library(cluster, "/usr/local/lib/R/site-library")
library(Seurat, lib.loc = lib.loc)
library(ggplot2, lib.loc = lib.loc)
library(reshape2, lib.loc = lib.loc)
library(parallel, lib.loc = lib.loc)
library(ape, "/usr/local/lib/R/site-library")
library(ggtree, lib.loc = lib.loc)
library(org.Hs.eg.db, lib.loc = lib.loc)
library(bluster, lib.loc = lib.loc)
library(SummarizedExperiment, lib.loc = lib.loc)
library(ggrepel, lib.loc = lib.loc)
```



```{r}
d <- get(load(file = "raw_data/Hao_2021/Hao_2021.RData"))
```


```{r, echo = T}
A <- d@reductions$pca@cell.embeddings[, 1:15]
```


```{r, echo = T}
# meta data
meta <- d@meta.data
```


```{r, echo = T}
markers_rna <- as.matrix(t(d@assays$SCT@data[
  rownames(d@assays$SCT@data) %in% 
    c("IL7R", 
      "CD14", "LYZ", 
      "MS4A1", 
      "CD8A", 
      "GNLY", "NKG7",
      "FCGR3A", "MS4A7",
      "FCER1A", "CST3",
      "PPBP", 
      "NCAM1", "CD27"), ]))
```

```{r, echo = T}
markers_adt <- as.matrix(t(d@assays$ADT@data))
```



```{r}
k20 <- get(load("~/scBubbletree/case_study_B/k20.RData"))
```


```{r}
e1 <- get_num_feature_tiles(btd = k20,
                            fs = markers_rna,
                            summary_function = "mean",
                            round_digits = 1,
                            rotate_x_axis_labels = T,
                            show_hclust = F,
                            disable_hclust = T,
                            tile_text_size = 2.5,
                            x_axis_name = 'RNA')
e1$w
```


  


```{r}
# CD3-1 = T cells
# CD19 = B cells
# CD14 = CD14+ monocytes
# CD56-1 = NK cells
# CD11c = dendritic cells (DCs) and monocytes

e2 <- get_num_feature_tiles(btd = k20,
                                     fs = markers_adt[, c("CD3-1", "CD4-1", "CD8",
                                                          "CD19", "CD27", "IgM", "IgD",
                                                          "CD14", "CD16", 
                                                          "CD56-1","CD11c")],
                                     summary_function = "mean",
                                     round_digits = 1,
                                     rotate_x_axis_labels = T,
                                     show_hclust = F,
                                     disable_hclust = T,
                                     tile_text_size = 2.5,
                                     x_axis_name = 'ADT')
```


```{r}
e2$w
```



```{r}
ggsave(filename = "manuscript_data/Supplementary_RNA_ADT.pdf",
       plot = (e1$w|e2$w)+patchwork::plot_layout(widths = c(1,1))+patchwork::plot_annotation(tag_levels = 'A'),
       device = "pdf",
       width = 6.5,
       height = 7)
```





```{r}

e3 <- get_cat_feature_tiles(btd = k20,
                            f = meta$Phase,
                            integrate_vertical = F,
                            round_digits = 1,
                            show_hclust = F,
                            disable_hclust = T,
                            tile_text_size = 2.75,
                            x_axis_name = "Cell cycle phase",
                            rotate_x_axis_labels = F)
```


```{r}
e3$w
```









<!-- ```{r, fig.width=14, fig.height=20} -->
<!-- e2 <- ((k20$tree|get_num_feature_tiles(btd = k20, -->
<!--                                        fs = markers_adt[, 1:(1+56)], -->
<!--                                        round_digits = 1, -->
<!--                                        rotate_x_axis_labels = T, -->
<!--                                        show_hclust = F, -->
<!--                                        disable_hclust = T, -->
<!--                                        tile_text_size = 2.5, -->
<!--                                        x_axis_name = '')$w)+ -->
<!--          patchwork::plot_layout(widths = c(3, 20)))/ -->
<!--   ((k20$tree|get_num_feature_tiles(btd = k20, -->
<!--                                        fs = markers_adt[, 58:(58+56)], -->
<!--                                        round_digits = 1, -->
<!--                                        rotate_x_axis_labels = T, -->
<!--                                        show_hclust = F, -->
<!--                                        disable_hclust = T, -->
<!--                                        tile_text_size = 2.5, -->
<!--                                        x_axis_name = '')$w)+ -->
<!--          patchwork::plot_layout(widths = c(3, 20)))/ -->
<!--   ((k20$tree|get_num_feature_tiles(btd = k20, -->
<!--                                        fs = markers_adt[, 115:(115+56)], -->
<!--                                        round_digits = 1, -->
<!--                                        rotate_x_axis_labels = T, -->
<!--                                        show_hclust = F, -->
<!--                                        disable_hclust = T, -->
<!--                                        tile_text_size = 2.5, -->
<!--                                        x_axis_name = '')$w)+ -->
<!--          patchwork::plot_layout(widths = c(3, 20)))/ -->
<!--   ((k20$tree|get_num_feature_tiles(btd = k20, -->
<!--                                        fs = markers_adt[, 172:(172+56)], -->
<!--                                        round_digits = 1, -->
<!--                                        rotate_x_axis_labels = T, -->
<!--                                        show_hclust = F, -->
<!--                                        disable_hclust = T, -->
<!--                                        tile_text_size = 2.5, -->
<!--                                        x_axis_name = '')$w)+ -->
<!--          patchwork::plot_layout(widths = c(3, 20))) -->

<!-- e2 -->
<!-- ``` -->


<!-- ```{r, fig.width=14, fig.height=20} -->
<!-- ggsave(filename = "manuscript_data/Supplementary_ADT.pdf", -->
<!--        plot = e2, -->
<!--        device = "pdf", -->
<!--        width = 13, -->
<!--        height = 25) -->
<!-- ``` -->





```{r}
mt <- meta$mt
names(mt) <- "MT[%]"

rna_count <- meta$nCount_RNA/1000
names(rna_count) <- "RNA count"

gene_count <- meta$nFeature_RNA
names(gene_count) <- "Gene count"


sup_w <- (get_num_feature_violins(btd = k20,
                                  fs = mt,
                                  rotate_x_axis_labels = F,
                                  x_axis_name = "MT [%]")$w|
            get_num_feature_violins(btd = k20,
                                    fs = rna_count,
                                    rotate_x_axis_labels = F,
                                    x_axis_name = "RNA count (in thousand)")$w|
            get_num_feature_violins(btd = k20,
                                    fs = gene_count,
                                    rotate_x_axis_labels = F,
                                    x_axis_name = "Gene count")$w
)
```


```{r, fig.width=6, fig.height=7}
sup_w <- sup_w+patchwork::plot_annotation(tag_levels = 'A')
sup_w
```



```{r, fig.width=6, fig.height=7}
ggsave(plot = sup_w,
       filename = "manuscript_data/Supplementary_QC_B.pdf",
       device = "pdf",
       width = 6.5,
       height = 6.5)
```




```{r}
a <- paste0(meta$donor, '(', meta$time, ')')

# a <- paste0(meta$donor)

# a <- a[order(a)]
# a <- factor(x = a, levels = sort(unique(a)))
sup_comp <- get_cat_feature_tiles(btd = k20,
                                  f = a,
                                  integrate_vertical = T,
                                  x_axis_name = 'Sample',
                                  round_digits = 1,
                                  rotate_x_axis_labels = T,
                                  show_hclust = F,
                                  disable_hclust = T,
                                  tile_text_size = 2.5)

```


```{r}
sup_comp$w
```





```{r, fig.width=6, fig.height=7}
ggsave(plot = sup_comp$w,
       filename = "manuscript_data/Supplementary_Composition_B.pdf",
       device = "pdf",
       width = 6.5,
       height = 6)
```






